theme: minima

title: Test Github Pages
author: Kittipos
email: ki11ip0.s.a.s@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Lightbridge-KS Test Github page

# social links
github_username:  Lightbridge-KS # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
